server:
  port: 9999
  servlet:
    context-path: /crm
#配置数据库连接信息
spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    url: jdbc:mysql://localhost:3306/crm?unicode=true&characterEncoding=utf8&serverTimeZone=Asia/shanghai&useSSL=true
    username: root
    password: root@123456
    #配置freeMarker页面访问路径
  freemarker:
    template-loader-path: classpath:/views/
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
  #开启热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
#配置分页插件方言
pagehelper:
  helper-dialect: mysql
#配置mybatis mappers文件映射 开启别名包扫描  开启下划线驼峰命名
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.zwf.crm.pojo;com.zwf.crm.vo;com.zwf.crm.query
  configuration:
    map-underscore-to-camel-case: true
#配置日志等级
logging:
  level:
    com:
      zwf:
        crm:
          dao: info
  file:
    name: logs/logging.log


